project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('simpleapp.urls')),
]

project/simpleapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.urls import reverse

class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    author_rating = models.IntegerField(default=0)

    def update_rating(self):
        postRAT = self.post_set.aggregate(post_rating=Sum('rating'))
        pRat = 0
        pRat += postRAT.get('post_rating')

        commentRAT = self.author.comment_set.aggregate(comm_rating=Sum('rating'))
        cRat = 0
        cRat += commentRAT.get('comm_rating')

        self.author_rating = pRat * 3 + cRat
        self.save()

    def __str__(self): #Метод для очеловечивания вывода из БД
        return '{}'.format(self.author.username) #Форматирование строк - защита от SQL инъекций

    class Meta:           #Класс для удобства админки
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class Category(models.Model):
    category_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return '{}'.format(self.category_name)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Post(models.Model):
    news = 'NE'
    article = 'AR'
    POSITIONS = [
        (news, 'Новость'),
        (article, 'Статья'),
    ]
    author_post = models.ForeignKey(Author, on_delete=models.CASCADE)
    type_choice = models.CharField(max_length=2, choices=POSITIONS, default=news)
    post_create_time = models.DateTimeField(auto_now_add=True)
    post_category = models.ManyToManyField(Category, through='PostCategory')
    post_header = models.CharField(max_length=128)
    post_text = models.TextField()
    post_rating = models.IntegerField(default=0)

    def like(self):
        self.post_rating += 1
        self.save()

    def dislike(self):
        self.post_rating -= 1
        self.save()

    def preview(self):
        return self.post_text[0:40] + '...'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def __str__(self):
        return '{}'.format(self.post_header)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.post, self.category)

class Comment(models.Model):
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    comm_create_time = models.DateTimeField(auto_now_add=True)
    comm_rating = models.IntegerField(default=0)

    def like(self):
        self.comm_rating += 1
        self.save()

    def dislike(self):
        self.comm_rating -= 1
        self.save()

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    class Subscription(models.Model):
        user = models.ForeignKey(
            to=User,
            on_delete=models.CASCADE,
            related_name='subscriptions',
        )
        category = models.ForeignKey(
            to='Category',
            on_delete=models.CASCADE,
            related_name='subscriptions',
        )

project/templates/article_create.html
<{% extends 'flatpages/default.html' %}

{% block title %} Создание статьи {% endblock title %}

{% block content %}
<h3>Создайте статью здесь!</h3>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Добавить статью">
</form>
{% endblock content %}

project/templates/articles_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.post_header }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

project/templates/articles_edit.html
<{% extends 'flatpages/default.html' %}

{% block title %} Изменение статьи {% endblock title %}

{% block content %}
<h3>Измените статью здесь!</h3>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Изменить статью">
</form>
{% endblock content %}

project/templates/news_create.html
<{% extends 'flatpages/default.html' %}

{% block title %} Создание новости {% endblock title %}

{% block content %}
<h3>Создайте новость здесь!</h3>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Добавить новость">
</form>
{% endblock content %}

project/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.post_header }}"?</p>
    <input type="submit" value="удалить" />
</form>
{% endblock content %}

project/templates/news_edit.html
<{% extends 'flatpages/default.html' %}

{% block title %} Изменение новости {% endblock title %}

{% block content %}
<h3>Измените новость здесь!</h3>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Изменить новость">
</form>
{% endblock content %}

project/templates/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
{{ object.post_header }}
{% endblock title %}

{% block content %}
<h1>{{ post.post_header|censor }} ({{ post.type_choice }})</h1>
<h2>{{ post.post_create_time|date:'M d Y' }}</h2>
<hr>
<h1>{{post.post_text|censor}}</h1>
<hr>
{% if post.type_choice == 'NE' %}
    {% if perms.simpleapp.change_product %}
    <a href="{% url 'news_edit' pk=post.id %}">Изменить</a>
    {% endif %}
    {% if perms.simpleapp.delete_product %}
    <a href="{% url 'news_delete' post.id %}">Удалить</a>
    {% endif %}
{% elif post.type_choice == 'AR' %}
    {% if perms.simpleapp.change_product %}
    <a href="{% url 'articles_edit' pk=post.id %}">Изменить</a>
    {% endif %}
    {% if perms.simpleapp.delete_product %}
    <a href="{% url 'articles_delete' post.id %}">Удалить</a>
    {% endif %}
{% endif %}
{% endblock content %}

project/templates/post_search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Поиск поста
{% endblock title %}

{% block content %}
    <hr>
     <form method="GET">
            {{ filter.form }}
            <input type="submit" value="Найти">
        </form>
            <table>
                <thead>
                    <th>Заголовок публикации</th>
                    <th>Дата публикации</th>
                    <th>Предварительный просмотр</th>
                    <th>Категории</th>
                </thead>
                {% for posts in filter.qs %}
                    <tr>
                        <td>
                            <a href="{% url 'post_detail' posts.id %}">{{ posts.post_header|title|censor }}</a>
                        </td>
                        <td>{{ posts.post_create_time|date:'M d Y'}}</td>
                        <td>{{ posts.post_text|truncatechars:20|censor }}</td>
                        <td>{{ posts.type_choice }}</td>
                    </tr>
                {% endfor %}
            </table>
{% endblock content %}

project/templates/posts.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Все посты
{% endblock title %}

{% block content %}
   <h1>Все новости и статьи</h1>
   <hr>
   <h2>Всего постов: {{posts|length}}</h2>
   <hr>
   {% if perms.simpleapp.add_post %}
      <a href="{% url 'news_create' %}">Добавить новость</a> <a href="{% url 'article_create' %}">Добавить статью</a>
   {% endif %}
   {% if posts %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Предварительный просмотр</td>
               <td>Автор</td>
               <td>Категория</td>
               <td>Рейтинг</td>
               <td>Тип поста</td>
           </tr>
           {% for post in posts %}
           <tr>
               <td>
                   <a href="{% url 'post_detail' post.id %}"> {{ post.post_header|censor }}</a>
               </td>
               <td>{{ post.post_create_time|date:'M d Y' }}</td>
               <td>{{ post.post_text|truncatechars:20|censor }}</td>
               <td>{{ post.author_post }}</td>
               <td>{{ post.post_category.get.category_name }}</td>
               <td>{{ post.post_rating }}</td>
               <td>{{ post.type_choice }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h1>Авторы пока не потрудились написать ни одного поста!</h1>
   {% endif %}
    {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

project/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Подписка на категорию
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.category_name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}